// client/src/components/common/GlobalControlsComponent.tsx
import * as React from 'react';
import { inject } from 'inversify';
import TYPES from '../../ioc/types';
import { Bus } from 'src/domain/entities/Bus';

export class GlobalControlsComponent extends React.Component {
  public gainAmount = 5;
  public tempo: number;
  public isPlaying: boolean;
  public resolution = 4;
  public gain = 100;
  public onToggleScheduler: any;

  @inject(TYPES.Bus) private bus: Bus;

  render() {
    return (
      <div className="col s12">
      <label>Gain:</label>
      <div className="input-field">
        <p className="range-field">
          <input type="range" min="0.0" max="100.0" step="{{gainAmount}}" value="gain" />
        </p>
      </div>
    </div>
    )
  }

  changeGainValue(amount: number) {
    if ((this.gain === 0 && amount < 1) || (this.gain === 100 && amount > 1)) {
      return;
    }

    this.gain += amount;
    this.bus.gainChannel.next(amount);
  }
}

// src/app/components/global-controls/global-controls.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormControl} from '@angular/forms';
import {Bus} from '../../domain/entities/Bus';

@Component({
  selector: 'app-global-controls',
  template: `
    <div class="col s12">
      <label>Gain:</label>
      <div class="input-field">
        <p class="range-field">
          <input type="range" min="0.0" max="100.0" step="{{gainAmount}}" [(ngModel)]="gain">
        </p>
      </div>
    </div>
  `
})
export class GlobalControlsComponent implements OnInit {
  public gainAmount = 5;
  public tempo: number;
  public isPlaying: boolean;
  public resolution = 4;
  public gain = 100;
  @Output() public onToggleScheduler = new EventEmitter<boolean>();

  constructor(private bus: Bus) {
  }

  ngOnInit() {
  }

  changeGainValue(amount: number) {
    if ((this.gain === 0 && amount < 1) || (this.gain === 100 && amount > 1)) {
      return;
    }

    this.gain += amount;
    this.bus.gainChannel.next(amount);
  }
}

<div class="col s3">
  <div class="switch">
    <label>
      Scheduler
      <input type="checkbox" [formControl]="schedulerMode">
      <span class="lever"></span>
      Metronome
    </label>
  </div>

</div>

<div class="col s6">
  <label>Gain:</label>
  <div class="input-field">
    <p class="range-field">
      <input type="range" min="0.0" max="100.0" step="{{gainAmount}}" [(ngModel)]="gain">
    </p>
  </div>
</div>
