// client/src/components/common/NavBarComponent.tsx
import * as React from 'react';
import { withStyles } from '@material-ui/core/styles';
import AppBar from '@material-ui/core/AppBar';
import Toolbar from '@material-ui/core/Toolbar';
import Typography from '@material-ui/core/Typography';
import Button from '@material-ui/core/Button';
import IconButton from '@material-ui/core/IconButton';
import MenuIcon from '@material-ui/icons/Menu';
// import { inject } from 'inversify';
// import TYPES from '../../../ioc/types';
// import { UserRepository } from 'src/domain/services/UserRepository';
// import { LoginService } from 'src/domain/services/LoginService';

const styles = {
  root: {
    flexGrow: 1,
  },
  grow: {
    flexGrow: 1,
  },
  menuButton: {
    marginLeft: -12,
    marginRight: 20,
  },
};

const NavBar = class NavBar extends React.Component<any, any> {
  user: any;

  // @inject(TYPES.UserRepository) public userRepository: UserRepository;
  // @inject(TYPES.LoginService) private loginService: LoginService

  render() {
    const { classes } = this.props;

    return (
      <div className={classes.root}>
        <AppBar position="static">
          <Toolbar>
            <IconButton className={classes.menuButton} color="inherit" aria-label="Menu">
              <MenuIcon />
            </IconButton>
            <Typography variant="title" color="inherit" className={classes.grow}>
              Programmable Metronome
              </Typography>
            <Button color="inherit">Login</Button>
          </Toolbar>
        </AppBar>
      </div>
    )

    // return (
    //   <nav>
    //     <div className="nav-wrapper">
    //       <a href="#" className="brand-logo hide-on-small-only">Programmable Metronome</a>
    //       <a href="#" className="brand-logo hide-on-med-and-up">Metronome</a>
    //       <ul id="nav-mobile" className="right hide-on-med-and-down">
    //         <li>
    //           {
    //             this.user ?
    //               <a className="waves-effect waves-light btn" onClick={() => this.logout()}>Logout</a>
    //               :
    //               <a className="waves-effect waves-light btn" onClick={() => this.login()}>Login</a>
    //           }
    //         </li >
    //       </ul >
    //     </div >
    //   </nav >
    // )
  }

  componentWillMount() {
    // this.userRepository.user.subscribe(x => {
    //   this.user = x;
    // });
  }

  login() {
    // this.loginService.login();
  }

  logout() {
    // this.loginService.logout();
  }
}

export default withStyles(styles)(NavBar);

// src/app/common/nav-bar/nav-bar.component.ts
import {Component, OnInit} from '@angular/core';
import {LoginService} from '../../domain/services/LoginService';
import {UserRepository} from '../../domain/services/UserRepository';

@Component({
  selector: 'app-nav-bar',
  providers: [LoginService],
  template: `
    <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo hide-on-small-only">Programmable Metronome</a>
        <a href="#" class="brand-logo hide-on-med-and-up">Metronome</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <div *ngIf="user; then loggedUserBlock else unloggedUserBlock"></div>
            <ng-template #unloggedUserBlock>
              <a class="waves-effect waves-light btn" (click)="login()">Login</a>
            </ng-template>
            <ng-template #loggedUserBlock>
              <a class="waves-effect waves-light btn" (click)="logout()">Logout</a>
            </ng-template>
          </li>
        </ul>
      </div>
    </nav>
  `
})
export class NavBarComponent implements OnInit {
  user: any;

  constructor(public userRepository: UserRepository, private loginService: LoginService) {
  }

  ngOnInit() {
    this.userRepository.user.subscribe(x => {
      this.user = x;
    });
  }

  login() {
    this.loginService.login();
  }

  logout() {
    this.loginService.logout();
  }
}
